@echo off
rem
rem  Sets up the JGMOD package for building with MSVC, and converting 
rem  text files from LF to CR/LF format.
rem

echo Converting JGMOD files to Windows (MSVC) format...

echo # generated by fixmsvc.bat > .\src\makefile
echo include makefile.vc >> .\src\makefile

echo # generated by fixmsvc.bat > .\examples\makefile
echo include makefile.vc >> .\examples\makefile


utod ...\*.bat ...\*.c  ...\*.h ...\*.scv
utod ...\*.txt ...\makefile.* ...\readme.* ...\plugins.*

echo Done!
echo.
