@echo off
rem
rem  Sets up the JGMOD package for building with MingW32, and converting 
rem  text files from LF to CR/LF format.
rem

echo Converting JGMOD files to Windows (MingW32) format...

echo # generated by fixming.bat > .\src\makefile
echo include makefile.mgw >> .\src\makefile

echo # generated by fixming.bat > .\examples\makefile
echo include makefile.mgw >> .\examples\makefile


echo Done!
echo.
